#!/usr/bun/python3
#    				return = جای گذاری مقدار خروجی تابع

def volume(width = 1, length = 1, height = 1):
	return width * length * height
	
v = volume(2, 3, 5)
print(v)
print(volume(length = 4))


def swap(a, b):
#	c = a
#	a = b
#	b = c
#	return a, b
	return b, a
	
first = 5 
second = 8
#first, second = swap(first , second)
first, second = second, first
print(first)
print(second)
